<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTwmguu4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTwmguu4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTwmguu4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTwmguu4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTwmguu4\appProdProjectContainer([
    'container.build_hash' => 'Twmguu4',
    'container.build_id' => '8a6aea3d',
    'container.build_time' => 1596386663,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTwmguu4');
